merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:band_id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:band_id>/update/', views.band_update, name='band-update'),
    path('bands/<int:band_id>/delete/', views.band_delete, name='band-delete'),
    path('about-us/', views.about, name='about-us'),
    path('listings/', views.listings_list, name='listing-list'),
    path('listings/<int:title_id>/', views.listings_detail, name='listing-detail'),
    path('listings/add/', views.listings_create, name='listing-create'),
    path('listings/<int:title_id>/update', views.listings_update, name='listing-update'),
    path('listings/<int:title_id>/delete', views.listings_delete, name='listing-delete'),
    path('contact-us/', views.contact, name='contact'),
    path('redirection/', views.redirection)
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Band(models.Model):
    def __str__(self) -> str:
        return f'{self.nom}'

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        RYTHM_AND_BLUES = 'RB'
        SOUL = 'S'
        JAZZ = 'J'
        RUMBA = 'R'
        SALSA = 'SA'
    
    class Type_annoucement(models.TextChoices):
        RECORDS = 'REC'
        CLOTHING = 'Clothes'
        POSTERS = 'Posters'
        MISCELLANEOUS = 'Miscellaneous'

    nom = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    annee_de_creation = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2024)])
    active = models.fields.BooleanField(default=True)
    page_officielle = models.fields.URLField(null=True, blank=True)
    type = models.fields.CharField(choices=Type_annoucement.choices, max_length=20)
    description  = models.fields.CharField(blank = True, max_length=1000)
    


class Title(models.Model):
    def __str__(self) -> str:
        return f'{self.title}'
    
    class Type_annoucement(models.TextChoices):
        RECORDS = 'REC'
        CLOTHING = 'Clothes'
        POSTERS = 'Posters'
        MISCELLANEOUS = 'Miscellaneous'
    
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL) #params : Band est le modele auquel on veut se rattacher ; 
                                                                         # null=True parce que nous voulons la creation de l'annonce meme si elles ne sont directements liees a un groupe ; 
                                                                         # on_delete=models.SET_NULL c'est ici que nous decidons de la strategie a suivre lorsque les objects Band sont supprimes. 
     
    title = models.CharField(max_length=100)
    description = models.fields.CharField(max_length=800)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(null=True, blank=True)
    type = models.fields.CharField(choices=Type_annoucement.choices, max_length=20)
    

merchex/listings/forms.py
from django import forms
from listings.models import Band
from listings.models import Title

class ContactUsForm(forms.Form):
    nom = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):    # generer automatiquement un formulaire a partir d'un modele avec un ModelForm
    class Meta:
        model = Band    # cette classe specifie le modele pour lequel ce formulaire sera utilise, et les champs de ce modele a inclure dans ce formulaire(dans ce cas, c'est tous)
       # fields = '__all__'
        exclude = ('active', 'official_homepage') # si vous voulez exclure certains des autres champs(non nullables) du formulaire, vous devrez d'abord leur donner une valeur par defaut, ou les rendre nullables.

class TitleForm(forms.ModelForm):
    class Meta:
        model = Title
        fields = '__all__'
        

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band, Title
from listings.forms import ContactUsForm, BandForm, TitleForm
from django.core.mail import send_mail
from django.shortcuts import redirect


def band_list(request):
    bands = Band.objects.all()
    return render(request, 
            'listings/band_list.html',
            {'bands': bands})
def band_detail(request, band_id):  
    band = Band.objects.get(id=band_id) # on insere cette ligne pour obtenir le Band avec cet id
    return render(request, 'listings/band_detail.html', {'band': band}) # on passe l'id au modele
def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid(): 
        # creer une nouvelle band et la sauvegarder dans la db    
            band = form.save() # la methode form.save() ne fait pas qu'enregistrer le nouvel objet dans la db : elle renvoie egalement cet objet, ce qui signifie que nous pouvons l'utiliser a l'etape suivante, ou nous redirigeons immediatement vers le groupe nouvellement cree.
            return redirect('band-detail', band.id)  # redige vers la page de detail du groupe que nous venons de creer, nous pouvons fournir les arguments du motif url comme arguments a la fonction de redirection.
    else:    
        form = BandForm()
        return render(request, 'listings/band_create.html', {'form': form}) 
def band_update(request, band_id):
    band = Band.objects.get(id=band_id)
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return redirect('band-detail', band.id)
    else:   
        form = BandForm(instance=band) 
        return render(request, 'listings/band_update.html', {'form': form})
def band_delete(request, band_id):
    band = Band.objects.get(id=band_id)
    if request.method == 'POST':
        band.delete()
        return redirect('band-list')
    else:
        return render(request, 'listings/band_delete.html', {'band': band})

def about(request):
    return render(request, 'listings/about-us.html')

def listings_list(request):
    titles = Title.objects.all()
    return render(request, 
            'listings/listings_list.html',
            {'titles': titles})
def listings_detail(request, title_id):
    title = Title.objects.get(id=title_id)
    return render(request, 'listings/listings_detail.html', {'title': title})
def listings_create(request):
    if request.method == 'POST':
        form = TitleForm(request.POST)
        if form.is_valid():
            title = form.save()
            return redirect('listing-detail', title.id)
    else:
        form = TitleForm()
        return render(request, 'listings/listings_create.html', {'form': form})
def listings_update(request, title_id):
    title = Title.objects.get(id=title_id)
    if request.method == 'POST':
        form = TitleForm(request.POST, instance=title)
        if form.is_valid():
            form.save()
            return redirect('listing-detail', title.id)
    else:
        form = TitleForm(instance=title)
        return render(request, 'listings/listings_update.html', {'form': form})
def listings_delete(request, title_id):
    title = Title.objects.get(id=title_id)
    if request.method == 'POST':
        title.delete()
        return redirect('listing-list')
    else:
        return render(request, 'listings/listings_delete.html', {'title': title})

def redirection(request):
    return render(request, 'listings/redirection.html')

def contact(request):
    
    if request.method == 'POST':    
        form = ContactUsForm(request.POST)
        if form.is_valid():    # si tout les champs de notre formulaire contiennent des donnees valides alors form.is_valid() renvoi True et nous appelons send_mail pour envoyer notre e-mail
            send_mail(
                subject=f'Message from{form.cleaned_data["name"] or "anonyme"}via MerchEx Contact Us form', # form cleaned_data est un dict contenant les donnees du formulaire apres qu'elles 
# ont subi le processus de validation. Lorsque nous sommes prets a faire quelque chose avec les donnees de notre formulaire, nous pouvons acceder a chacun des champs via form.cleaned_data['name_of_field] mais nous devons d'abord appeler form.is_valid() 
                message=form.cleaned_data["message"],
                from_email=form.cleaned_data["email"],
                recipient_list=['admin@merchex.xyz'],)
            return redirect(redirection) # lorsque le formulaire est valide et que le courriel a ete envoye, cette redirection guidera le navigateur de la page du formulaire vers une page de 
# de confirmation. c'est une page qui a un motif URL avec le nom email-sent. 
    else:
        form = ContactUsForm()
    return render(request, 'listings/contact-us.html', {'form': form})
 

merchex/listings/templates/listings/about-us.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>About-us</h1>
<p>We love merch!</p>
{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>creer un nouveau groupe</h1>

<form action ="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Soumettre">
</form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Supprimer ce groupe</h1>

<p>Etes-vous sur de vouloir supprimer le groupe : {{ band.nom }} ?</p>


<form action ="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ band.nom }}</h2>

<ul>
    <li>Genre : {{ band.get_genre_display}}</li>
    <li>Annee de creation : {{ band.annee_de_creation }}</li>
    <li>Actif : {{ band.active | yesno }}</li>
    {% if band.page_officielle %}
    <li><a href="{{ band.page_officielle}}">{{ band.page_officielle}}</a></li>
    {% endif %}
    {% if band.description %}
    <p>{{ band.description }}</p>
    {% endif %}
</ul>
    {% for title in band.title_set.all %} 
    <h4>Articles : </h4>
    <ul>
       
            <li>Annonce : {{ title.title }}</li>
            <li>Type : {{ title.get_type_display }} </li>     
        </ul>
        {% endfor %}

<a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>
<a href="{% url 'band-delete' band.id %}">Supprimer ce groupe</a>
<a href="{% url 'band-list' %}">Retour a tous les groupes</a>
{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>
<ul>
    {% for band in bands %}
    <li><a href="{% url 'band-detail' band.id %}">{{ band.nom }}</a></li>
    {% endfor %}
</ul>

{% endblock %}
 

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Mise a jour du groupe</h1>

<form action ="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Soumettre">
</form>



{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %} 

<html>
    <head><title>Merchex</title></head>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    <body>
        <nav>
            <a href="{% url 'band-list' %}" >Groupes</a>
            <a href="{% url 'listing-list' %}">Listes</a>
            <a href="{% url 'contact' %}">Contactez-nous</a>
            <a href="{% url 'about-us' %}">A propos</a>
            <a href="{% url 'band-create' %}">Creer un nouveau groupe</a>
            <a href="{% url 'listing-create' %}">Creer une nouvlle annonce</a>
        </nav>

        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/contact-us.html
{% extends 'listings/base.html' %}

{% block content %}


<p>Nous sommes la pour vous aider.</p>

<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Soumettre" />
</form>
 {% endblock %}
  

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Articles</h1> 
    <p>these are our products :
</p>
<ul>
    {% for title in titles %}
    <li>{{ title.title }}</li>
    {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/listings_create.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>creer une nouvelle annonce</h1>

<form action ="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Soumettre">
</form>

{% endblock %}

merchex/listings/templates/listings/listings_delete.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Supprimer cette annonce</h1>

<p>Etes-vous sur de vouloir supprimer l'annonce « {{ title.title }} » ?</p>


<form action ="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/listings_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ title.title }}</h2>

<ul>
    <li>Description : {{ title.description}}</li>
    <li>plein : {{ title.sold | yesno }}</li>
    {% if title.year %}
    <li>Annee : {{ title.year }}</li>
    {% endif %}
    <li>Type : {{ title.get_type_display}}</li>
</ul>

<a href="{% url 'listing-update' title.id %}">Modifier cette annonce</a>
<a href="{% url 'listing-delete' title.id %}">Supprimer cette annonce</a>
<a href="{% url 'band-list' %}">Retour a tous les groupes</a>
{% endblock %}

merchex/listings/templates/listings/listings_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Listes</h1>
<ul>
    {% for title in titles %}
    <li><a href="{% url 'listing-detail' title.id %}">{{ title.title }}</a></li>
    {% endfor %}
</ul>

{% endblock %}
 

merchex/listings/templates/listings/listings_update.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Mise a jour de l'annonce</h1>

<form action ="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Soumettre">
</form>

{% endblock %}